### PR TITLE
AvailableReservations/ReviewReservation/ConfirmReservation/Fixed Google Firebase

### LINKED ISSUE #27: Create an available reservations page for the user view

### LINKED ISSUE #49: Update the functions to reflect the updated database

### LINKED ISSUE #50: Create a Review Reservations page

### LINKED ISSUE #51: Create a reservation confirmation page/connect with review reservation and current reservation page

### PR DESCRIPTION
**Pull request by plstarkey18**
In this pull request, I updated the current functions to resemble the updated documents in our Google Firebase console. I also renamed the UserRes files to UserAvailableRes to better reflect what this page is showing. From there, I implemented expansion panels with a button letting the user reserve that technology. It brings them to a static review reservation page that displays the when, what time, and how long questions. Once that is completed, the submit button will lead them to a confirmation page. These pages are static, and the next steps are to populate them with information from our database.

### CODE REVIEW

File: src/App.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
   <v-app :style="{background: $vuetify.theme.themes.light.background}">
     <v-main>
-      <v-btn to="/UserView">
+      <v-btn to="/UserAvailableResView">
```
Comment (greyhixson) [inline src/App.vue]: Only two views will ever exist. Revert this change

File: src/components/User/UserRes.vue [hunk 2]
```diff
@@ -0,0 +1,192 @@
+<template>
```
Comment (greyhixson) [inline src/components/User/UserRes.vue]: There were some problems in this file, but it's Caity's file so I won't address them twice here since she'll be the one fixing them.

File: src/router/index.js [hunk 3]
```diff
@@ -1,15 +1,18 @@
 import Vue from 'vue';
 import VueRouter from 'vue-router';
 import AdminView from '../views/AdminView.vue';
-import UserView from '../views/UserView.vue';
+import UserAvailableResView from '../views/UserAvailableResView.vue';
+import UserConfirmResView from '../views/UserConfirmResView.vue';
+import UserResView from '../views/UserResView.vue';
+import UserReviewResView from '../views/UserReviewResView.vue';
```
Comment (greyhixson) [inline src/router/index.js]: Adding a view for every component is redundant. Only two views should exist and redirects to their components will exist in them.

File: src/router/index.js [hunk 4]
```diff
@@ -1,15 +1,18 @@
...
 Vue.use(VueRouter);
 
 const routes = [
   {
-    path: '/UserView',
-    name: 'UserView',
-    component: UserView,
+    path: '/UserAvailableResView',
+    name: 'UserAvailableResView',
+    component: UserAvailableResView,
```
Comment (greyhixson) [inline src/router/index.js]: Revert change

File: src/router/index.js [hunk 5]
```diff
@@ -21,6 +24,21 @@ const routes = [
...
+  {
+    path: '/UserReviewResView',
+    name: 'UserReviewResView',
+    component: UserReviewResView,
+  },
+  {
+    path: '/UserConfirmResView',
+    name: 'UserConfirmResView',
+    component: UserConfirmResView,
+  },
```
Comment (greyhixson) [inline src/router/index.js]: In the router, only two views will exist with each component. Having a view for every component is redundant and unnecessary.

File: src/views/UserAvailableResView.vue [hunk 6]
```diff
@@ -0,0 +1,15 @@
...
+import UserAvailableRes from '../components/User/UserAvailableRes.vue';
+
+export default {
+  name: 'UserAvailableResView',
+
+  components: {
+    UserAvailableRes,
+  },
+};
+</script>
```
Comment (greyhixson) [inline src/views/UserAvailableResView.vue]: File is unnecessary and should be deleted

File: src/views/UserConfirmResView.vue [hunk 7]
```diff
@@ -0,0 +1,15 @@
...
+import UserConfirmRes from '../components/User/UserConfirmRes.vue';
+
+export default {
+  name: 'UserConfirmResView',
+
+  components: {
+    UserConfirmRes,
+  },
+};
+</script>
```
Comment (greyhixson) [inline src/views/UserConfirmResView.vue]: File is unnecessary and should be deleted

File: src/views/UserResView.vue [hunk 8]
```diff
@@ -1,15 +1,14 @@
 <template>
-  <user-home />
+  <user-res />
```
Comment (greyhixson) [inline src/views/UserResView.vue]: Revert, UserHome contains available reservations and the user's reservations. User-res makes it seem like it's just their reservations.

File: src/views/UserResView.vue [hunk 9]
```diff
@@ -1,15 +1,14 @@
...
 </template>
 
 <script>
-import UserHome from '../components/User/UserHome.vue';
+import UserRes from '../components/User/UserRes.vue';
```
Comment (greyhixson) [inline src/views/UserResView.vue]: Revert

File: src/views/UserResView.vue [hunk 10]
```diff
@@ -1,15 +1,14 @@
...
 
 export default {
   name: 'UserView',
-
   components: {
-    UserHome,
+    UserRes,
```
Comment (greyhixson) [inline src/views/UserResView.vue]: Revert

File: src/views/UserReviewResView.vue [hunk 11]
```diff
@@ -0,0 +1,15 @@
...
+import UserReviewRes from '../components/User/UserReviewRes.vue';
+
+export default {
+  name: 'UserReviewResView',
+
+  components: {
+    UserReviewRes,
+  },
+};
+</script>
```
Comment (greyhixson) [inline src/views/UserReviewResView.vue]: File is unnecessary and should be deleted

**Review by greyhixson — CHANGES_REQUESTED** [review]
You made the same mistake that everyone else made so no worries there, but your code initially seems clear of any bugs so good job.

File: src/App.vue (hunk 1 above)
Comment (plstarkey18) [reply src/App.vue:4]: This button was originally going to the UserHome, which view was called UserView. I just changed the name in this to reflect the new name of UserAvailableResView. UserView no longer exists.

File: src/views/UserView.vue [hunk 12]
```diff
@@ -1,15 +1,15 @@
 <template>
-  <user-home />
+  <user-available-res />
```
Comment (greyhixson) [inline src/views/UserView.vue]: This page may not just be what is currently on it. It is the user's home with reservations available to them but it may be more than that in the future, so for now just leave it as user-home so it's clear that it is the user's landing component.

File: src/components/User/UserReviewRes.vue [hunk 13]
```diff
@@ -0,0 +1,77 @@
...
+      >
+        Sign Out
+      </v-btn>
+    </v-row>
+    <v-card>
+      <v-toolbar
+        color="#01579B"
+        dark
+      >
+        <v-toolbar-side-icon />
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue]: `<v-toolbar-side-icon />` doesn't exist

File: src/components/User/UserReviewRes.vue [hunk 14]
```diff
@@ -0,0 +1,77 @@
...
+            label="Date?"
+            prepend-icon="mdi-calendar"
+            readonly
+            v-bind="attrs"
+            v-on="on"
+          />
+        </template>
+        <v-date-picker
+          v-model="date"
+          @input="menu2 = false"
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue:66]: `menu2` doesn't exist check console log for details when you visit this page

File: src/components/User/UserReviewRes.vue [hunk 15]
```diff
@@ -0,0 +1,77 @@
...
+            v-model="date"
+            label="Date?"
+            prepend-icon="mdi-calendar"
+            readonly
+            v-bind="attrs"
+            v-on="on"
+          />
+        </template>
+        <v-date-picker
+          v-model="date"
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue:65]: `date` doesn't exist check console log for details when you visit this page

File: src/components/User/UserReviewRes.vue [hunk 16]
```diff
@@ -0,0 +1,77 @@
...
+        />
+      </v-menu>
+      <v-select
+        :items="items"
+        label="Time?"
+        prepend-icon="mdi-clock"
+      />
+      <v-select
+        :items="items"
+        label="Duration?"
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue]:
```suggestion
        label="Duration"
```

File: src/components/User/UserReviewRes.vue [hunk 17]
```diff
@@ -0,0 +1,77 @@
...
+          />
+        </template>
+        <v-date-picker
+          v-model="date"
+          @input="menu2 = false"
+        />
+      </v-menu>
+      <v-select
+        :items="items"
+        label="Time?"
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue]:
```suggestion
        label="Time"
```

File: src/components/User/UserReviewRes.vue [hunk 18]
```diff
@@ -0,0 +1,77 @@
...
+        :close-on-content-click="false"
+        :nudge-right="40"
+        transition="scale-transition"
+        offset-y
+        min-width="auto"
+      >
+        <template v-slot:activator="{ on, attrs }">
+          <v-text-field
+            v-model="date"
+            label="Date?"
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue]:
```suggestion
            label="Date"
```

File: src/components/User/UserReviewRes.vue [hunk 19]
```diff
@@ -0,0 +1,77 @@
...
+    <v-card>
+      <v-toolbar
+        color="#01579B"
+        dark
+      >
+        <v-toolbar-side-icon />
+        <v-toolbar-title>Apple MacBook Air</v-toolbar-title>
+      </v-toolbar>
+      <v-menu
+        v-model="menu2"
```
Comment (greyhixson) [inline src/components/User/UserReviewRes.vue:47]: `menu2` doesn't exist check console log for details when you visit this page

**Review by greyhixson — CHANGES_REQUESTED** [review]
Good work on the functions, but there were quite a few errors in your UserReviewRes component. Please be mindful when copying code from vuetify's website and elsewhere because you wrote several properties that don't exist. Every line and every piece of a line are meaningful and once we start making things dynamic it'll be a problem if things are written without understanding why they are there, and what purpose they serve.

**Comment by greyhixson** [comment]
Branch is out of date with master and still hasn't addressed my previous comments on UserReviewRes
@plstarkey18 
Look right below this comment and you'll see '19 conversations must be resolved before merging.' and then click through them and either hit resolve or if it's something new fix it and then hit resolve.

**Review by greyhixson — APPROVED** [review]
Fantastic job.
Resolving merge conflicts can be tricky but you handled it perfectly.
